### ISSUE TITLE
Split Event into Event + EventSubscriber

### ISSUE THREAD

**Issue by marktanner1331** [aryehof/dart-event#1]
I would find it very useful if the implementation of Event was split into two classes:
One for managing event subscriptions, and one for doing the broadcasting. 

It would protect the event from being broadcasted unintentionally:
for example:
`Event _e = Event();
EventSubscription get e => _e;`

**Comment by aryehof** [comment]
@marktanner1331 Just curious... under what circumstances do you envisage an event might be broadcast unintentionally? From within some custom framework that used dart events, or something else?

**Comment by marktanner1331** [comment]
@aryehof I'm making my own poker game, and hoping to make it open source so that people can write their own AI players. The main table controller class will contain all the events of what is happening in the game. 
My fear is that an AI might try and cheat by broadcasting events on the table itself, and confusing the other players.

**Comment by aryehof** [comment]
If required, I think that this is best implemented by a user extending the existing Event class. In the majority of cases, it would introduced unneeded complexity.
