### ISSUE TITLE
Nullable event args

### ISSUE THREAD

**Issue by ryuujo1573** [aryehof/dart-event#10]
Why event can be emitted without EventArgs? 
This is not ideal, for mainly non nullable values are used.
```
typedef EventHandler<T extends EventArgs> = void Function(T? args);
```
Emit an event without arguments is meaningless. 
I suggest use required positional argument `T` instead. For those cases void values are used, just use `Event<SomeType?>` on `Event<T extends EventArgs?>`

**Comment by aryehof** [comment]
> Why event can be emitted without EventArgs?

Traditional MVC by convention has a view query the model after being notified that some event has occurred, rather than include whats changed/happened with the notification.
