### ISSUE TITLE
Unsubscribe not working

### ISSUE THREAD

**Issue by felixkriechbaum** [aryehof/dart-event#11]
I have been using the package for a few days now and I noticed that unsubscribe NEVER works.

I create my Event with
```dart
Event myEvent = Event();
```

Then I subscribe with
```dart
myEvent.subscribe((v) => print("MESSAGE: ${DateTime.now()}"));
```

Fire(broadcast) with:
```dart
myEvent.broadcast();
```

Then I unsubscribe with
```
myEvent.unsubscribe((a) {
    print("unsubscribe");
});
```

in my humble opinion I am using this package correct. But unsubscribe returns every time 'false' and also unsubscribe doesn't unsubscribe, when I subscribe, unsubscribe and subscribe again I have to listeners to the same event. Instead of one.

I attached a demo project to showcase my problem

[event_temp_demo.zip](https://github.com/aryehof/dart-event/files/11193854/event_temp_demo.zip)

**Comment by aryehof** [comment]
Your providing an anonymous function to both subscribe and unsubscribe. One can only unsubscribe a _named_ handler. In other words, unsubscribe needs a reference to an _existing_ handler.
