### ISSUE TITLE
Unsubscribe/dispose?

### ISSUE THREAD

**Issue by MostHated** [aryehof/dart-event#3]
What is the proper way to unsubscribe/dispose of a listener? I have a number of listeners setup on different classes that are used as needed, but for instance, the one below is used on the login page, then once it is completed, this page will have a replacement pushed in place of it, and I am not sure how to properly get rid of the event listener. 

There are other ones in a few places that listen to the same one and do other things, which was why I have it in a get_it instance, so I definitely don't want to unsubscribe all of them or remove the event broadcasting class.

```dart
  final sl = GetIt.instance;
  final authStatus = sl<AuthStatusListener>();
    
  @override
  void initState() {
    super.initState();

    authStatus.event +
        (args) => () {
              if (authStatus.isSignIn) {
                Future.microtask(() => _routeTransitionController.forward()).then((value) {
                  Navigator.of(context).pushReplacement(FadePageRoute(builder: (context) => DashboardScreen()));
                  authStatus.setStatus(AuthStatus.signedIn);
                });
              }
            }();
  }

  @override
  void dispose() {
    if (!_isDisposed) {
      authStatus.event.unsubscribe(this); // Not sure exactly what to put here?
    }
    _isDisposed = true;
    super.dispose();
  }

```
Thanks,
-MH

**Comment by aryehof** [comment]
I'm not entirely sure of the context, but consider explicitly declaring the handler, then subscribe to it in initState() and unsubscribe in dispose().

```dart
var statusHandler = (args) -> { /*code here*/};

void initState() {
  // ...
 authStatus.event.subscribe(statusHandler);
}

void dispose() {
  // ...
  authStatus.event.unsubscribe(statusHandler);
}
```

**Comment by MostHated** [comment]
That is just what I was looking for, thank you.

**Comment by aryehof** [comment]
Anytime. If you want to have a chat sometime about events/service locator/flutter, would be interesting to hear your thoughts. If so, let me know.

**Comment by MostHated** [comment]
Sure thing. I am headed to bed now, but tomorrow or any other time, really, works for me. I am @killmenext on twitter or my username here at instance.id for email.

**Comment by MostHated** [comment]
Hey there, I had one additional "best practice" question. Is there any difference, be it beneficial or adverse, to having multiple events, members, or broadcasters within the same class? The only thing I remember hearing that was in some way similar was that it was either bad practice or had an actual negative impact on your application to have multiple notifysenders() within a single change notifier class. 

The reason I ask is that in the past I found some of my changenotifier classes become relatively large, mostly due to convenience and I want to try and avoid that, but also, not be too overly concerned so as to make sure every single event, broadcaster, and member were always fully separated if they didn't exactly need to be.

This was what I was just working on when I felt it might be a good idea to ask before I went too much further. I just added a second event to the ExpansionController, is that fine, or should I get in the habit of just creating a new small separate class?

```dart
class ExpansionListener {
  bool value = false;
  String type;
  var valueChangedEvent = Event();

  void sendMessage(bool value, String type) {
    this.value = value;
    this.type = type;
    valueChangedEvent.broadcast();
  }
}

class ExpansionController {
  ExpandTarget target = ExpandTarget.NONE;
  var _numOpen = 0;

  get isNone => target == ExpandTarget.NONE;
  get isNews => target == ExpandTarget.NEWS;
  get isChangeLog => target == ExpandTarget.CHANGELOG;
  get numOpen => _numOpen;

  final valueChangedEvent = Event();
  final numOpenEvent = Event();

  void setNumOpen(int value) {
    this._numOpen = value;
    numOpenEvent.broadcast();
  }

  void expandTarget(ExpandTarget value) {
    this.target = value;
    valueChangedEvent.broadcast();
  }
}

```

Thanks!
-MH

**Comment by aryehof** [comment]
I wouldn't overthink it. Events are lightweight. If your domain/problem abstraction merits lots of events, add them. If not, don't.
