### ISSUE TITLE
unsubscribe always return false

### ISSUE THREAD

**Issue by thetnswe** [aryehof/dart-event#4]
Hi, once I've subscribed to an event, I can't unsubscribe anymore and the events are still receiving even when my class is disposed... 

Here is the sample test code
class DownloadManager {
  static final allVideosDownloadedEvent = Event();
}

DownloadManager.allVideosDownloadedEvent.subscribe((args) {
//Event received when the allVideosDownloadedEvent  is broatcasted
    });

//Trying to unsubscrive just for testing
    bool bStatus = DownloadManager.allVideosDownloadedEvent.unsubscribe((args) {});
    if(bStatus)
      print('Exrecise details viewModel unsubscribed to download manager event!');
    else
    {
//This one always triggered
      print('Oops! Cant subscribed');
    }

**Comment by aryehof** [comment]
Unsubscribe needs to receive an *existing* event handler. Your passing the unsubscribe method a *new* event handler (an anonymous function) - one that hasn't been subscribed to.

To unsubscribe you need to keep a reference to the handler passed to the subscribe method, and provide that to the unsubscribe method.

See also the answer at https://github.com/aryehof/dart-event/issues/3#issuecomment-641934884

**Comment by thetnswe** [comment]
Thanks for the prompt response. Noted and thanks alot.

With Best Regards,
Thet Naing Swe
Founder & Chief Technical Officer
Twitter: @thetnswe

Company info:
URL: http://joydash.com
Twitter : @JoyDashGames <http://twitter.com/JoyDashGames>
Fan page: http://www.facebook.com/JoyDashGames

**Comment by aryehof** [comment]
Most welcome. Nice to see your in Singapore, my wife was born there and I'm originally from Perth. Think of me next time your having chilli crab. Wish I was there :)

**Comment by thetnswe** [comment]
Of course....Actually, I am mostly resided in Myanmar.. Contact me if
you've a chance to visit there and I will be there for you :)

With Best Regards,
Thet Naing Swe
Founder & Chief Technical Officer
Twitter: @thetnswe

Company info:
URL: http://joydash.com
Twitter : @JoyDashGames <http://twitter.com/JoyDashGames>
Fan page: http://www.facebook.com/JoyDashGames
