### ISSUE TITLE
Subscribe once and exception.

### ISSUE THREAD

**Issue by itschrono** [aryehof/dart-event#5]
Hello,

version: 1.3.4.
I need to subscribe "once" and I did implement it like this:
```dart
wsApi.onLogin.subscribe((args) {
      Logger.log({args});
      wsApi.onLogin.unsubscribeAll();
});
```

But I get the execption: 
```
Unhandled Exception: Concurrent modification during iteration: Instance(length:0) of '_GrowableList'
```

I guess I cannot call `unsubscribeAll` while subscriber are being called (because of iteration).
A `subscribeOnce` method would really be helpful. `_handlers` should never be set to null and always initialized. And to remove a handler or all handler you may use: https://api.dart.dev/stable/2.10.4/dart-core/List/removeWhere.html <- this can be done while iterating ;)

**Comment by aryehof** [comment]
@itschrono I'm reluctant to add a "subscribeOnce" method. It represents an additional choice any subscriber must understand and think about i.e. "should I subscribe or should I subscribeOnce, and in what scenarios should each be used or not used?"

I'm unclear why one would really want to subscribe _once_?

**Comment by mkorbel1** [comment]
Subscribing once is useful to have something happen upon the next occurrence of an event.  Creating a Future that waits for the next occurrence of an event requires creating a Completer, subscribing it to the event to mark it completed, and triggering an unsubscribe upon Completer completion, which is a lot of overhead.  It would be nice if Event had both a "subscribeOnce" type of function as well as a Future that triggered on the next event instance.

**Comment by aryehof** [comment]
@mkorbel1 For now I've removed the iterator based calling of each subscribed handler in 2.0.5. This allows the unsubscribeAll method to be called from within a handler without an exception, per the original issue.

Is it possible to create another issue re your comment?

**Comment by mkorbel1** [comment]
Sure, filed here: https://github.com/aryehof/dart-event/issues/8
Thanks!
