### ISSUE TITLE
unsubscribe and unsubscribeAll crash when event has never been subscribed to

### ISSUE THREAD

**Issue by mkorbel1** [aryehof/dart-event#7]
The code for unsubscribeAll in event.dart (below) assumes (!) handlers is non-null, but if there has never been a subscription to the event then handlers is null.

https://github.com/aryehof/dart-event/blob/048d37bf22a1d0363bef700da138f6e293570061/lib/src/event.dart#L120-L124

This causes a crash with "Null check operator used on a null value".

I think the same bug exists for unsubscribe:
https://github.com/aryehof/dart-event/blob/048d37bf22a1d0363bef700da138f6e293570061/lib/src/event.dart#L79-L81

**Comment by aryehof** [comment]
Thanks for reporting that.
