### ISSUE TITLE
subscribeOnce and Future for next event occurence

### ISSUE THREAD

**Issue by mkorbel1** [aryehof/dart-event#8]
It would be helpful to be able to do something once when an event occurs.  Two possible use cases are:
- subscribeOnce: just like subscribe except it only triggers it once
- Future: some Future method that completes upon the next instance of the event, so that it can be 'await'ed

**Comment by aryehof** [comment]
@mkorbel1 So just to clarify ... are you talking about something that supports the following, where calling broadcast on the Event causes the Future returned by subscribeOnce to complete, and to also unsubscribe the handler?
```dart
      var e = Event();
      Future f = e.subscribeOnce((args) => {});
      e.broadcast();  // causes the Future f to complete
      f.whenComplete(() => print('done'));

// calling e.broadcast() now would do nothing because
// the handler has been unsubscribed on the first broadcast?

**Comment by mkorbel1** [comment]
Yes, that looks great to me.  Can the future also return the same args?

**Comment by aryehof** [comment]
@mkorbel1 Yes the future can provide the args, e.g.

```dart
var e = Event<Value>();  //use the provided EventArg derived 'Value'
var f= e.subscribeOnce((args) => {});
e.broadcast(Value(77));
f.then((val) => print(val.value));

// outputs the number 77
// val.whenOccurred and val.description are also available because Value is derived from StdEventArgs
```

What I'm hazy about is how useful this functionality is. Can you provide an example or two of where you would use it? Is the need for this widespread?

**Comment by mkorbel1** [comment]
One hypothetical example: a game where the first time a token is acquired, a tutorial pop-up appears explaining what the token does.  Of course you could implement something similar without Events, or subscribe forever and check a boolean if you've already displayed it to prevent showing it multiple times, but if Events are cleaner implementation then subscribing once is more convenient than storing a boolean or unsubscribing afterwards.  The future can be used in similar situations where some independent progress through an async function is gated by the next occurrence of an event.

I don't have data about how widespread the need for it is, but two users (myself and  itscrono from https://github.com/aryehof/dart-event/issues/5) of this package were interested enough to file issues to support it.

**Comment by aryehof** [comment]
Reluctant to implement this and add complexity via further Event methods, as one can use unsubscribeAll or a stream (via subscribeStream) to achieve effectively the same thing.
